FROM debian:8

MAINTAINER <ale-batt@student.42.fr>

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y nmap
RUN apt-get install -y libpcap-dev
RUN apt-get install -y tcpdump

#ADD . /app
#ADD libft /app
#ADD libnetwork /app
WORKDIR /app

VOLUME /app
